# example values

server:
  port: 8080
spring:
  datasource:
    username: root
    password: pass4MySQL
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
indexing-settings:
  sites:
    - url: https://radiomv.ru/
      name: Милицейская волна
    - url: https://dombulgakova.ru/
      name: Булкаковский дом
    - url: https://dimonvideo.ru
      name: Всё для мобильных устройств
    - url: https://www.playback.ru/
      name: Интернет - магазин PlayBack.ru
    - url: https://nikoartgallery.com
      name: Креативное пространство и галерея Н.Б. Никогосяна
